source "https://rubygems.org"

gem "rake"
gem "ruboty-alias"
gem "ruboty-cron"
gem "ruboty-google_image"
gem "ruboty-redis"
gem "ruboty-redis-info"
gem "ruboty-slack"
gem "ruboty-echo"
gem 'ruboty-ec2', :git => 'git://github.com/DreamArtsOkinawa/dabot.git', :branch => "ruboty-ec2"
